package com.lym.springboot.web.core.mapper;

import com.lym.springboot.web.core.domain.WebAdmin;
import com.lym.springboot.web.core.domain.WebAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    long countByExample(WebAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    int deleteByExample(WebAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    int insert(WebAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    int insertSelective(WebAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    WebAdmin selectOneByExample(WebAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    WebAdmin selectOneByExampleSelective(@Param("example") WebAdminExample example, @Param("selective") WebAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    List<WebAdmin> selectByExampleSelective(@Param("example") WebAdminExample example, @Param("selective") WebAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    List<WebAdmin> selectByExample(WebAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    WebAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WebAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    WebAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    WebAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WebAdmin record, @Param("example") WebAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WebAdmin record, @Param("example") WebAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WebAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WebAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") WebAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}