package com.lym.springboot.web.core.mapper;

import com.lym.springboot.web.core.domain.WebLog;
import com.lym.springboot.web.core.domain.WebLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    long countByExample(WebLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    int deleteByExample(WebLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    int insert(WebLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    int insertSelective(WebLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    WebLog selectOneByExample(WebLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    WebLog selectOneByExampleSelective(@Param("example") WebLogExample example, @Param("selective") WebLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    List<WebLog> selectByExampleSelective(@Param("example") WebLogExample example, @Param("selective") WebLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    List<WebLog> selectByExample(WebLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    WebLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WebLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    WebLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    WebLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WebLog record, @Param("example") WebLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WebLog record, @Param("example") WebLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WebLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WebLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") WebLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}