package com.lym.springboot.web.core.mapper;

import com.lym.springboot.web.core.domain.WebMenuPermissionRe;
import com.lym.springboot.web.core.domain.WebMenuPermissionReExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebMenuPermissionReMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    long countByExample(WebMenuPermissionReExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    int deleteByExample(WebMenuPermissionReExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    int insert(WebMenuPermissionRe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    int insertSelective(WebMenuPermissionRe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    WebMenuPermissionRe selectOneByExample(WebMenuPermissionReExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    WebMenuPermissionRe selectOneByExampleSelective(@Param("example") WebMenuPermissionReExample example, @Param("selective") WebMenuPermissionRe.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    List<WebMenuPermissionRe> selectByExampleSelective(@Param("example") WebMenuPermissionReExample example, @Param("selective") WebMenuPermissionRe.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    List<WebMenuPermissionRe> selectByExample(WebMenuPermissionReExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    WebMenuPermissionRe selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WebMenuPermissionRe.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    WebMenuPermissionRe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WebMenuPermissionRe record, @Param("example") WebMenuPermissionReExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WebMenuPermissionRe record, @Param("example") WebMenuPermissionReExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WebMenuPermissionRe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WebMenuPermissionRe record);

    /**
     * 批量保存
     * @param menuPermissionRes
     * @return
     */
    int insertBatch(@Param("menuPermissionRes") List<WebMenuPermissionRe> menuPermissionRes);
}