package com.lym.springboot.web.core.mapper;

import com.lym.springboot.web.core.domain.WebMenu;
import com.lym.springboot.web.core.domain.WebMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    long countByExample(WebMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    int deleteByExample(WebMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    int insert(WebMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    int insertSelective(WebMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    WebMenu selectOneByExample(WebMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    WebMenu selectOneByExampleSelective(@Param("example") WebMenuExample example, @Param("selective") WebMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    List<WebMenu> selectByExampleSelective(@Param("example") WebMenuExample example, @Param("selective") WebMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    List<WebMenu> selectByExample(WebMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    WebMenu selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WebMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    WebMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    WebMenu selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WebMenu record, @Param("example") WebMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WebMenu record, @Param("example") WebMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WebMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WebMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") WebMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}