package com.lym.springboot.web.core.mapper;

import com.lym.springboot.web.core.domain.WebRole;
import com.lym.springboot.web.core.domain.WebRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    long countByExample(WebRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    int deleteByExample(WebRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    int insert(WebRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    int insertSelective(WebRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    WebRole selectOneByExample(WebRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    WebRole selectOneByExampleSelective(@Param("example") WebRoleExample example, @Param("selective") WebRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    List<WebRole> selectByExampleSelective(@Param("example") WebRoleExample example, @Param("selective") WebRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    List<WebRole> selectByExample(WebRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    WebRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WebRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    WebRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    WebRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WebRole record, @Param("example") WebRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WebRole record, @Param("example") WebRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WebRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WebRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") WebRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}