package com.lym.springboot.web.core.mapper;

import com.lym.springboot.web.core.domain.WebSystem;
import com.lym.springboot.web.core.domain.WebSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    long countByExample(WebSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    int deleteByExample(WebSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    int insert(WebSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    int insertSelective(WebSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    WebSystem selectOneByExample(WebSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    WebSystem selectOneByExampleSelective(@Param("example") WebSystemExample example, @Param("selective") WebSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    List<WebSystem> selectByExampleSelective(@Param("example") WebSystemExample example, @Param("selective") WebSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    List<WebSystem> selectByExample(WebSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    WebSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WebSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    WebSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WebSystem record, @Param("example") WebSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WebSystem record, @Param("example") WebSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WebSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WebSystem record);
}