package com.lym.springboot.web.core.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class WebMenuPermissionRe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_menu_permission_re.id
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_menu_permission_re.menu_id
     *
     * @mbg.generated
     */
    @ApiModelProperty("菜单ID")
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_menu_permission_re.permission_id
     *
     * @mbg.generated
     */
    @ApiModelProperty("权限ID")
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_menu_permission_re.api_uri
     *
     * @mbg.generated
     */
    @ApiModelProperty("后台接口地址uri")
    private String apiUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_menu_permission_re.front_url
     *
     * @mbg.generated
     */
    @ApiModelProperty("前端链接地址")
    private String frontUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_menu_permission_re.add_time
     *
     * @mbg.generated
     */
    @JsonIgnore
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_menu_permission_re.update_time
     *
     * @mbg.generated
     */
    @JsonIgnore
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_menu_permission_re.id
     *
     * @return the value of web_menu_permission_re.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_menu_permission_re.id
     *
     * @param id the value for web_menu_permission_re.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_menu_permission_re.menu_id
     *
     * @return the value of web_menu_permission_re.menu_id
     *
     * @mbg.generated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_menu_permission_re.menu_id
     *
     * @param menuId the value for web_menu_permission_re.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_menu_permission_re.permission_id
     *
     * @return the value of web_menu_permission_re.permission_id
     *
     * @mbg.generated
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_menu_permission_re.permission_id
     *
     * @param permissionId the value for web_menu_permission_re.permission_id
     *
     * @mbg.generated
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_menu_permission_re.api_uri
     *
     * @return the value of web_menu_permission_re.api_uri
     *
     * @mbg.generated
     */
    public String getApiUri() {
        return apiUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_menu_permission_re.api_uri
     *
     * @param apiUri the value for web_menu_permission_re.api_uri
     *
     * @mbg.generated
     */
    public void setApiUri(String apiUri) {
        this.apiUri = apiUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_menu_permission_re.front_url
     *
     * @return the value of web_menu_permission_re.front_url
     *
     * @mbg.generated
     */
    public String getFrontUrl() {
        return frontUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_menu_permission_re.front_url
     *
     * @param frontUrl the value for web_menu_permission_re.front_url
     *
     * @mbg.generated
     */
    public void setFrontUrl(String frontUrl) {
        this.frontUrl = frontUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_menu_permission_re.add_time
     *
     * @return the value of web_menu_permission_re.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_menu_permission_re.add_time
     *
     * @param addTime the value for web_menu_permission_re.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_menu_permission_re.update_time
     *
     * @return the value of web_menu_permission_re.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_menu_permission_re.update_time
     *
     * @param updateTime the value for web_menu_permission_re.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", menuId=").append(menuId);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", apiUri=").append(apiUri);
        sb.append(", frontUrl=").append(frontUrl);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WebMenuPermissionRe other = (WebMenuPermissionRe) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMenuId() == null ? other.getMenuId() == null : this.getMenuId().equals(other.getMenuId()))
            && (this.getPermissionId() == null ? other.getPermissionId() == null : this.getPermissionId().equals(other.getPermissionId()))
            && (this.getApiUri() == null ? other.getApiUri() == null : this.getApiUri().equals(other.getApiUri()))
            && (this.getFrontUrl() == null ? other.getFrontUrl() == null : this.getFrontUrl().equals(other.getFrontUrl()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
        result = prime * result + ((getPermissionId() == null) ? 0 : getPermissionId().hashCode());
        result = prime * result + ((getApiUri() == null) ? 0 : getApiUri().hashCode());
        result = prime * result + ((getFrontUrl() == null) ? 0 : getFrontUrl().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table web_menu_permission_re
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        menuId("menu_id", "menuId", "INTEGER", false),
        permissionId("permission_id", "permissionId", "INTEGER", false),
        apiUri("api_uri", "apiUri", "VARCHAR", false),
        frontUrl("front_url", "frontUrl", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table web_menu_permission_re
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}